### ISSUE TITLE
Respiteful causing mixin issues with debugify

### ISSUE THREAD

**Issue by border999** [LimonBlaze/Respiteful#3]
respiteful-1.18.2-1.1.0
debugify-1.11.0-forge-1.18.2

**Comment by RaymondBlaze** [comment]
See: https://github.com/murao-kun/Debugify-reforged/pull/7
Debugify was shading MixinExtras, it did relocated the lib, but it didn't use `mergeServiceFiles`, resulting in broken classload due to module conflicts.
For a temporary fix, open your `debugify-1.11.0-forge-1.18.2.jar` and delete `META-INF/services/javax.annotation.processing.Processor`.
